### ISSUE TITLE
Desafio #4 - Entradas/Saídas incorretas.

### ISSUE THREAD

**Issue by SidiBecker** [he4rtlabs/he4rtoberfest-2020#106]
Olá. As entradas e saídas do desafio estão incorretas. Seguem abaixo resultados corretos para o desafio se baseando ao site referenciado:

```
Quantidade de casos de teste: 6

Número de posições do caso 1: 2
Mensagem do caso 1: VQREQFGT

Número de posições do caso 2: 10
Mensagem do caso 2: ABCDEFGHIJKLMNOPQRSTUVWXYZ

Número de posições do caso 3: 0
Mensagem do caso 3: TOPCODER

Número de posições do caso 4: 25
Mensagem do caso 4: ZWBGLZ

Número de posições do caso 5: 1
Mensagem do caso5: DBNPCBQ

Número de posições do caso 6: 4
Mensagem do caso 6: LIPPSASVPH


Resultados:
TOPCODER
QRSTUVWXYZABCDEFGHIJKLMNOP
TOPCODER
AXCHMA
CAMOBAP
HELLOWORLD
```

Ou seja, está faltando o input da quantidade de casos que deverão ser informados, que no site seria aquele primeiro número 6, e os números de posição estão trocados. Se necessário eu realizo um PR realizando a correção.

**Comment by jonatasosilva** [comment]
E aí, SidiBecker.

Acabei de atualizar, mas se quiser melhorar fica a vontade.

**Comment by SidiBecker** [comment]
> E aí, SidiBecker.
> 
> Acabei de atualizar, mas se quiser melhorar fica a vontade.

Valeu @jonatasosilva. Seria isso mesmo. Obrigado!
